const test=require('node:test');
const assert=require('node:assert/strict');
const {openDatabase}=require('../src/db');
const {AmulSync,DATASETS}=require('../src/services/amul-sync');
const {ERPService}=require('../src/services/erp-service');
test('POS MRP includes GST and keeps wholesale pricing separate',()=>{
 const db=openDatabase(':memory:');const erp=new ERPService(db);
 const p=erp.createProduct({sku:'MRP',name:'Cup',retailPrice:35,wholesalePrice:30,mrpPrice:40,gstBps:1800});
 const s=erp.createParty({partyType:'SUPPLIER',name:'Supplier'});
 erp.receivePurchase({supplierId:s.id,items:[{productId:p.id,quantity:10,unitCost:20,batchNumber:'B'}]});
 const sale=erp.createInvoice({channel:'RETAIL',priceMode:'MRP',items:[{productId:p.id,quantity:3,unitPrice:1}],payments:[{method:'CASH',amount:120}]});
 const d=erp.invoiceDetail(sale.id);
 assert.equal(d.invoice.total_paise,12000);
 assert.equal(d.invoice.subtotal_paise+d.invoice.cgst_paise+d.invoice.sgst_paise,12000);
 assert.equal(d.items[0].unit_price_paise,4000);assert.equal(d.items[0].tax_inclusive,1);
 assert.equal(erp.getProduct(p.id).wholesale_price_paise,3000);
 erp.editInvoice(sale.id,{reason:'Keep bill unchanged',items:[{productId:p.id,quantity:3,unitPrice:40,gstBps:1800,taxInclusive:true}]});
 assert.equal(erp.invoiceDetail(sale.id).invoice.total_paise,12000);
 db.close();
});
test('local invoice correction preserves invoice and payment identity and adjusts ledger and stock',()=>{
 const db=openDatabase(':memory:');const erp=new ERPService(db);
 const p=erp.createProduct({sku:'P',name:'Cup',retailPrice:10,wholesalePrice:10,gstBps:0});
 const s=erp.createParty({partyType:'SUPPLIER',name:'Supplier'}), c=erp.createParty({name:'Customer'});
 erp.receivePurchase({supplierId:s.id,items:[{productId:p.id,quantity:20,unitCost:5,batchNumber:'B'}]});
 const sale=erp.createInvoice({channel:'DISTRIBUTION',customerId:c.id,items:[{productId:p.id,quantity:2}],payments:[{method:'CASH',amount:10}]});
 erp.editInvoice(sale.id,{reason:'Correct count',items:[{productId:p.id,quantity:3,unitPrice:12}]});
 assert.equal(erp.invoiceDetail(sale.id).invoice.total_paise,3600);
 assert.equal(erp.invoiceDetail(sale.id).invoice.paid_paise,1000);
 assert.equal(erp.listProducts()[0].stock_qty,17);
 assert.equal(erp.listParties('CUSTOMER')[0].balance_paise,2600);
 assert.throws(()=>erp.editInvoice(sale.id,{reason:'Too many',items:[{productId:p.id,quantity:100}]}),/Insufficient/);
 assert.equal(erp.listProducts()[0].stock_qty,17);
 assert.equal(erp.invoiceDetail(sale.id).invoice.total_paise,3600);
 db.close();
});
test('invoice corrections update stock and dues atomically and survive full sync',async()=>{
 const db=openDatabase(':memory:');
 const datasets=Object.fromEntries(DATASETS.map(k=>[k,[]]));
 datasets.products=[{PrdId:1,PrdName:'Cup'}];
 datasets.batches=[{PrdBatId:10,PrdId:1}];
 datasets.stock=[{PrdId:1,PrdBatID:10,LcnId:1,PrdBatLcnSih:10}];
 datasets.invoices=[{SalId:1,SalInvNo:'INV1',SalInvDate:'2026-09-09',SalNetAmt:20,RtrId:1}];
 datasets.invoice_lines=[{SalId:1,SlNo:1,PrdId:1,PrdBatId:10,BaseQty:2,PrdUnitSelRate:10,PrdNetAmount:20}];
 const sync=new AmulSync(db,{enabled:true,read:async()=>({datasets})});
 assert.equal(await sync.sync(),true);
 const input={reason:'Correct quantity',items:[{productId:'1',batchId:'10',quantity:3,unitPrice:12,taxAmount:2}]};
 sync.editInvoice('1',input);
 assert.equal(sync.invoiceDetail('1').invoice.total_paise,3800);
 assert.equal(db.prepare('SELECT stock_qty FROM amul_products_local').get().stock_qty,9);
 assert.equal(await sync.sync({full:true}),true);
 assert.equal(sync.invoiceDetail('1').items[0].quantity,3);
 assert.equal(db.prepare('SELECT stock_qty FROM amul_products_local').get().stock_qty,9);
 assert.throws(()=>sync.editInvoice('1',{...input,items:[{...input.items[0],quantity:100}]}),/Insufficient stock/);
 assert.equal(sync.invoiceDetail('1').invoice.total_paise,3800);
 assert.equal(db.prepare('SELECT stock_qty FROM amul_products_local').get().stock_qty,9);
 sync.editInvoice('1',{...input,items:[{...input.items[0],quantity:1}]});
 assert.equal(db.prepare('SELECT stock_qty FROM amul_products_local').get().stock_qty,11);
 await sync.stop();db.close();
});
test('customer edits preserve identity and audit changes',()=>{
 const db=openDatabase(':memory:');const erp=new ERPService(db);
 const p=erp.createParty({name:'Retailer',mobile:'9876543210'});
 const updated=erp.updateParty(p.id,{name:'New name',whatsappNumber:'919876543210',creditDays:5});
 assert.equal(updated.id,p.id);assert.equal(updated.code,p.code);assert.equal(updated.credit_days,5);
 assert.throws(()=>erp.updateParty(p.id,{name:''}),/Name is required/);
 assert.equal(erp.getParty(p.id).name,'New name');
 assert.equal(db.prepare("SELECT COUNT(*) n FROM audit_log WHERE action='UPDATE' AND entity_type='PARTY'").get().n,1);
 db.close();
});
test('available stock precedes old zero rows',()=>{
 const db=openDatabase(':memory:');const sync=new AmulSync(db,{enabled:false});
 const put=db.prepare('INSERT INTO amul_products_local(product_id,product_name,stock_qty,source_json) VALUES(?,?,?,?)');
 put.run('1','Available',5,'{}');
 for(let i=2;i<100;i++)put.run(String(i),'Empty',0,'{}');
 assert.equal(sync.pageLocal('amul_products_local').rows[0].product_id,'1');
 db.close();
});
test('original bill details preserve six decimal rates and recorded tax after edits',async()=>{
 const db=openDatabase(':memory:');
 const datasets=Object.fromEntries(DATASETS.map(k=>[k,[]]));
 datasets.products=[{PrdId:1,PrdName:'Cup'}];datasets.batches=[{PrdId:1,PrdBatId:10}];
 datasets.stock=[{PrdId:1,PrdBatID:10,LcnId:1,PrdBatLcnSih:100}];
 datasets.invoices=[{SalId:1,SalInvNo:'Old',SalInvDate:'2026-09-09',SalNetAmt:'271.999996',SalTaxAmount:'12.952380'}];
 datasets.invoice_lines=[{SalId:1,SlNo:1,PrdId:1,PrdBatId:10,BaseQty:32,PrdUnitMRP:10,PrdUnitSelRate:'8.095238',PrdTaxAmount:'12.952380',PrdNetAmount:'271.999996'}];
 const sync=new AmulSync(db,{enabled:true,read:async()=>({datasets})});assert.equal(await sync.sync(),true);
 let bill=sync.billDetail('1');
 assert.equal(bill.items[0].unit_rate_rupees,8.095238);
 assert.equal(bill.items[0].gross_paise,25905);
 assert.equal(bill.items[0].tax_paise,1295);
 assert.equal(bill.items[0].net_paise,27200);
 assert.equal(bill.items[0].purchase_reference,null);
 sync.editInvoice('1',{reason:'Local correction',items:[{productId:'1',batchId:'10',quantity:32,unitPrice:9,taxAmount:14.4}]});
 bill=sync.billDetail('1');
 assert.equal(bill.items[0].unit_rate_rupees,8.095238);
 assert.equal(bill.source_total_paise,27200);
 assert.equal(bill.locally_corrected,true);
 await sync.stop();db.close();
});
